import = ["~/.config/alacritty/tokyonight_moon.toml"]

live_config_reload = true

[font]
size = 12.0

[env]
TERM = "xterm-256color"

[terminal]
osc52 = "CopyPaste"

# See all available options with `fc-list : family`
[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"
[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"
[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"
[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"


[font.offset]
x = 1
y = 1

#[[hints.enabled]]
#command = { program = "xclip", args = [
#  "-selection",
#  "clipboard",
#], input = "replace" }

#[[hints.enabled]]
#action = "Copy"
#post_processing = false
#regex = '(([0-9a-f]{12,128})|([[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3})|("[^ ]+\\.rs:\\d+:\\d+))'
#mouse = { enabled = true }

#[hints.enabled.binding]
#key = "I"
#mods = "Control|Shift"
#

[mouse]
bindings = [
  # Double left-click to highlight a word (or triple for the whole line).
  # Then right click to paste.
  { mouse = "Right", action = "Paste" },
]

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "L", mods = "Control|Shift", chars = "l" },
]


[scrolling]
history = 50000

[selection]
save_to_clipboard = true

[window]
title = "Alacritty"
decorations = "full"
decorations_theme_variant = "dark"
#option_as_alt = "Both" # Not sure I need this.
dynamic_padding = false
opacity = 0.9

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
